Hotel_booking/Hotel_booking/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Hotel_booking_app.urls',namespace='hotel'))
]

Hotel_booking/Hotel_booking_app/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name='hotel'
urlpatterns = [
    path('',views.Home,name='home'),
    path('signin/',views.Sign_up,name='signin'),
    path('login/',views.Log_in,name='login'),
    
    path('profile/<int:id>/',views.Profile,name='profile'),
    path('logout/',views.log_out,name='logout'),
    path('userhome/',views.userhome,name='userhome'),
    path('update_profile/<int:id>/',views.ProfileUpdate.as_view(),name='update_profile'),
    path('search/',views.search_view.as_view(),name='search'),
    path('room/<str:hotel>/',views.Room_view,name='rooms')





] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hotel_booking/Hotel_booking_app/models.py
from datetime import datetime
from distutils.command.upload import upload
from email.policy import default
from enum import auto, unique
from random import choices
from secrets import choice
from django.db import models
from django.contrib.auth.models import AbstractUser
from . manager import *
from django.utils import timezone
# Create your models here.

class CustomeUser(AbstractUser):
    username=None
    GENDER_CHOICES=(
        ('M','Male'),
        ('F','Female'),
        ('OTHER','Other')
    )

    ROLL=(
        ('User','User'),
        ('Manager','Manager')
    )
    first_name=models.CharField(max_length=50,null=True,blank=True)
    last_name=models.CharField(max_length=50,null=True,blank=True)

    email=models.EmailField(unique=True)
    profile_image=models.ImageField(upload_to = "myProfiles",null=True,blank=True)
    mobile=models.CharField(max_length=12,null=True,blank=True)
    gender=models.CharField(choices=GENDER_CHOICES,max_length=10,null=True,blank=True)
    dob=models.DateField(default=timezone.now,null=True,blank=True)
    roll=models.CharField(choices=ROLL,max_length=10,default='User')
    address=models.CharField(max_length=100,null=True,blank=True)
    city=models.CharField(max_length=100,null=True,blank=True)
    state=models.CharField(max_length=100,null=True,blank=True)
    country=models.CharField(max_length=100,null=True,blank=True)



    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[]
    objects=CustomUserManager()

class Hotel(models.Model):
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=150,null=True,blank=True)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100,null=True,blank=True)
    country=models.CharField(max_length=100,null=True,blank=True)
    phone=models.CharField(max_length=12,null=True,blank=True)
    Hotel_image=models.ImageField(upload_to='hotel')
    available_rooms=models.IntegerField(default=1)
    rating=models.IntegerField(default=1)
    hotel_info=models.CharField(max_length=500,null=True,blank=True)

    def __str__(self) :
        return self.name

class Room(models.Model):
    Room_CHOICE=(
        ('SINGLE','SINGLE'),
        ('DOUBLE','DOUBLE'),
    )
    room_no=models.IntegerField(default=100)
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    room_type=models.CharField(choices=Room_CHOICE,max_length=20,default='SINGLE')
    room_image=models.ImageField(upload_to='rooms')
    room_price=models.FloatField()
    room_availability=models.BooleanField()
    room_info=models.CharField(max_length=500,null=True,blank=True)

    def __str__(self) :
        return self.room_type

class Booking(models.Model):
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomeUser,on_delete=models.CASCADE)
    select_room=models.ManyToManyField(Room)
    check_in=models.DateField()
    check_out=models.DateField()
    Adult=models.IntegerField(default=1)
    children=models.IntegerField(default=0)

   

Hotel_booking/Hotel_booking_app/forms.py
from dataclasses import field, fields
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from . models import *
class SignUpForm(UserCreationForm):
    class Meta:
        model=CustomeUser
        fields=['email']

class LoginForm(forms.Form):
   
    email=forms.EmailField()
    password=forms.CharField(widget=forms.PasswordInput)

    
  

# class ProfileForm(forms.ModelForm):

#     class  Meta:
#         model=CustomeUser
#         fields =['first_name','last_name','profile_image','gender','dob','email','mobile','roll','address','city','state','country',]

class UserForm(forms.ModelForm):
    class Meta:
        model = CustomeUser
        fields = ['first_name','last_name','profile_image','dob','roll','address','city','state','country']
class BookingForm(forms.ModelForm):

    class Meta:
        model=Booking
        fields='__all__'

Hotel_booking/Hotel_booking_app/views.py
from audioop import reverse
import email
import http
from unicodedata import name
from urllib import request
from django.shortcuts import redirect, render
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import CreateView
from django.views import View, generic
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.views.generic import DetailView

# Create your views here.

def Home(request):
    if not request.user.is_authenticated:
        return render(request,'home.html')
    
    else:
        return redirect('/userhome/')

def Sign_up(request):
    if request.method=='POST':
        fm=SignUpForm(request.POST)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect('/login/')
    else:
        fm=SignUpForm()

    return render(request,'signup.html',{'form':fm})


def Log_in(request):
    if request.method=='POST':
        fm=LoginForm(request.POST)
        if fm.is_valid():
            
          
            
            email=fm.cleaned_data['email']
            password=fm.cleaned_data['password']
            user=authenticate(password=password,email=email)

            if user is not None:
                login(request,user)
                # return HttpResponse('loged in')
                # st=CustomeUser.objects.all()
                # messages.success(request,'you are loged in!!{{user.first_name}}')
                return HttpResponseRedirect('/userhome/')
        else:
            er='Email/password is required'
            return render(request,'login.html',{'error':er})
    else:
        fm=LoginForm()
    return render(request,'login.html',{'form':fm})


def log_out(request):
    if request.method=="GET":
        logout(request)
        return redirect('/')


def Profile(request,id):
    # if request.user.is_authenticated:
       
    #     user=CustomeUser.objects.filter(id=request.user.id).first()
    #     # user=get_user_model.objects.all()
        
    #     fm=ProfileForm(instance=user)
       
    #     return render(request,'profile.html',{'users':fm})
    # else:
    #     return HttpResponseRedirect('/login/')

    if request.user.is_authenticated:
        user=CustomeUser.objects.get(pk=id)
        
        return render(request,'profile.html',{'users':user})

    else:
         return HttpResponseRedirect('/')
    # if request.method=="GET":
    #     user = CustomeUser.objects.get(pk=id)
    #     return render(request, 'profile.html',{'user':user})


def userhome(request):

    a=CustomeUser.objects.get(id=request.user
    .id)
    
    # import pdb;pdb.set_trace()
    return render(request,'userhome.html',{'qr':a})

    

# @csrf_exempt
# def Update_profile(request):
    
#         if request.method=='POST':
#             fm=ProfileForm(request.FILES,request.POST
#             )
#             # import pdb;pdb.set_trace()  
#             if fm.is_valid():
#                 fm.save()
#                 return HttpResponseRedirect('/userhome/')

        
#         else:
#             if request.user.is_authenticated:
#                fm=ProfileForm(instance=request.user)
#             else:
#                 return HttpResponseRedirect('/')
#         return render(request,'update_profile.html',{'form':fm})
    


def Forgetpassword(request):
        if request.method=='POST':
            fm=SetPasswordForm(user=request.user,data=request.POST)
            if fm.is_valid():
                fm.save()

                return http('password change successfully')
        
        else:
            fm=SetPasswordForm(user=request.user)
        return render(request,'forgetpassword.html',{'form':fm})
    
# def Update_profile1(request):
#     if request.method=="POST":
#         fm=ProfileForm(request.FILES,instance=request.user)
#         if fm.is_valid():
#             fm.save()
#             return HttpResponseRedirect('/userhome/')

#     else:
#         fm=ProfileForm(instance=request.user)

#     return render(request,'update_profile1.html',{'form':fm})

class ProfileUpdate(generic.View):
    def get(self, request,id, *args, **kwargs,):
        if request.user.is_authenticated:
            pi=CustomeUser.objects.get(pk=id)
            form = UserForm(instance=pi)
            return render(request,'update_profile.html',{'form':form})
        else:
            return redirect('/')

    def post(self, request,id, *args, **kwargs,):
        # user_details = CustomeUser.objects.get(id=request.user.id)
        pi=CustomeUser.objects.get(pk=id)
        form = UserForm(request.POST, request.FILES, instance=pi)
        if form.is_valid():
            
            form.save()
            return redirect('/userhome/')
        else:
            print("no")
        return render(request,'update_profile.html',{'form':form})


class search_view(ListView):
    model=Hotel
    template_name='search.html'

    def get_queryset(self) :

        result=super().get_queryset()
        query=self.request.GET.get('search')
        if Hotel.objects.filter(city=query):

            result=Hotel.objects.filter(city=query)
        else:
             result=Hotel.objects.filter(name=query)
        
        
        return result


# class Room_view(generic.View):
#     model=Room
#     template_name='room.html'

#     def get_queryset(self):
        
#             rm=Room.objects.all()
#             query=self.request.GET.get('hotel')
#             rm=rm.filter(hotel__name=query)
            
#             return rm
        

def Room_view(request,hotel):

    if request.method=='GET':
        rm=Room.objects.filter(hotel__name=hotel)

        return render(request,'room.html',{'object_list':rm})
    



class Booking_view(generic.View):

    def get(self,request,*args, **kwargs):
        if request.user.is_authenticated:
            fm=BookingForm()
            return render(request,'booking.html',{'form':fm})
        else:
            return redirect('/')

    def post(self,request,*args, **kwargs):
        fm=BookingForm()
        if fm.is_valid():
            fm.save()
            return redirect('/userhome/')
        else:
            print('no')
        return render(request,'booking.html',{'form':fm})

Hotel_booking/Hotel_booking_app/templates/forgetpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{form.as_p}}
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
        
        .topnav h1.cm {
            display: flex;
            justify-content: left;
            color: white;
            text-align: left;

        }
        .topnav {
            display: flex;
            background-color: blue;
            
            justify-content: space-between;
            padding-right: 12px;
            align-items: center;
        }
        .nav-items {
            width: 50%;
            display: flex;
            justify-content: right;
        }
        .nav-items a{
            color: white;
            padding: 12px;
        }
        .logo h1{
            color: white;
            padding-left: 25px;
        }
        .fakeimage {
            background-color: bisque;
            display: flex;
            justify-content: space-between;
            
        }
        .cm {
            background-color: white;
            display:flex;
            padding-top: 600px;
            
            background-image: url('docker images');
            background-size:100%100%;
            background-attachment:fixed;
        }

        .pro a{
            color: white;
            padding-left: 0%;
        }
        img{
            border-radius: 7px;
        }
        .logo h5{
            color: white;   
        }
    </style>
</head>
<body >
    
    <div  class="topnav">
       <div class="logo"><h1>Hotel.Com</h1>
          
    </div>
       
       <div class="nav-items">
        <a href="">Home</a>
       <a href="{% url 'hotel:signin' %}">Sign Up</a>
       <a href="{% url 'hotel:login' %}">Sign In</a>
      
       </div>
    </div>

    {% if messages %}
    {% for message in messages %}
    
    {{message}}
    {{request.user.first_name}}
    {% endfor %}
    {% endif %}
    <div  class="cm" style="background-image: url('../static/image/hotel.png.jpg');">
        <div class="fakeimage" style="height: 60px;column-width: auto;">
            <h1>Book</h1>
        </div>
    </div>
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        .er{
            color: red;
        }
    </style>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
       

       <p class="er">{{error}}</p>  <br>

        {% for fm in form %}
        
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
        
        {% endfor %}
     
       <input type="submit" value="Signin">
       <a href="">Forgepassword</a>
    </form>
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>

    
    {{users.get_full_name}} <br>
   
    {{users.email}} <br>

   <a href="{% url 'hotel:update_profile' id=users.id%}">Update Profile</a>
   <a href="{% url 'hotel:logout' %}">Logout</a>
   
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hotel</title>
    <style>
        /* .row{
    height: 500px;
    width: 100%;
    display: flex;
    justify-content: center;
    background-color: blue;
  }  
  .column{
    height: 350px;
    width: 100%;
    background-color: red;
    padding-bottom: 25px;
    display: inline;
  }    
.column1{
    width: 50%;
    height: 100%;
    float: left;
}
.column2{
    height: 100%;
    width: 50%;
    float: right;
} */
        .main {
            width: 100%;
            height: auto;
            display: flex;
            justify-content: center;

        }

        .main2 {
            width: 70%;
            height: auto;

        }

        .row {
            width: 100%;
            height: 350px;
            display: flex;

        }

        .column1 {
            width: 50%;
            height: 350px;
            background-color: green;
            border: 10px;
        }

        .column2 {
            width: 50%;
            height: 350px;
            background-color: rgb(148, 53, 53);
        }

        .nm {
            padding-left: 20px;
            padding-top: 1px;
            font-size: 30px;
        }

        .ct {
            padding-left: 20px;
            font-size: 30px;
        }

        .btn {
            background-color: green;
            color: white;

        }

        .btn1 {
            margin-right: 0px;
            margin-bottom: 0px;
            display: flex;
            justify-content: end;
            margin-top: 190px;
            /* margin-right: 10px; */
            /* margin-top: 40%; */

        }

        /* ========================================= */


        @import url("https://fonts.googleapis.com/css2?family=Baloo+2&display=swap");
/* This pen */
body {
  font-family: "Baloo 2", cursive;
  font-size: 16px;
  color: #ffffff;
  text-rendering: optimizeLegibility;
  font-weight: initial;
}

.dark {
  background: #110f16;
}

.light {
  background: #f3f5f7;
}

a, a:hover {
  text-decoration: none;
  transition: color 0.3s ease-in-out;
}

#pageHeaderTitle {
  margin: 2rem 0;
  text-transform: uppercase;
  text-align: center;
  font-size: 2.5rem;
}

/* Cards */
.postcard {
  flex-wrap: wrap;
  display: flex;
  box-shadow: 0 4px 21px -12px rgba(0, 0, 0, 0.66);
  border-radius: 10px;
  margin: 0 0 2rem 0;
  overflow: hidden;
  position: relative;
  color: #ffffff;
}
.postcard.dark {
  background-color: #18151f;
}
.postcard.light {
  background-color: #e1e5ea;
}
.postcard .t-dark {
  color: #18151f;
}
.postcard a {
  color: inherit;
}
.postcard h1, .postcard .h1 {
  margin-bottom: 0.5rem;
  font-weight: 500;
  line-height: 1.2;
}
.postcard .small {
  font-size: 80%;
}
.postcard .postcard__title {
  font-size: 1.75rem;
}
.postcard .postcard__img {
  max-height: 180px;
  width: 100%;
  object-fit: cover;
  position: relative;
}
.postcard .postcard__img_link {
  display: contents;
}
.postcard .postcard__bar {
  width: 50px;
  height: 10px;
  margin: 10px 0;
  border-radius: 5px;
  background-color: #424242;
  transition: width 0.2s ease;
}
.postcard .postcard__text {
  padding: 1.5rem;
  position: relative;
  display: flex;
  flex-direction: column;
}
.postcard .postcard__preview-txt {
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: justify;
  height: 100%;
}
.postcard .postcard__tagbox {
  display: flex;
  flex-flow: row wrap;
  font-size: 14px;
  margin: 20px 0 0 0;
  padding: 0;
  justify-content: center;
}
.postcard .postcard__tagbox .tag__item {
  display: inline-block;
  background: rgba(83, 83, 83, 0.4);
  border-radius: 3px;
  padding: 2.5px 10px;
  margin: 0 5px 5px 0;
  cursor: default;
  user-select: none;
  transition: background-color 0.3s;
}
.postcard .postcard__tagbox .tag__item:hover {
  background: rgba(83, 83, 83, 0.8);
}
.postcard:before {
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-image: linear-gradient(-70deg, #424242, transparent 50%);
  opacity: 1;
  border-radius: 10px;
}
.postcard:hover .postcard__bar {
  width: 100px;
}

@media screen and (min-width: 769px) {
  .postcard {
    flex-wrap: inherit;
  }
  .postcard .postcard__title {
    font-size: 2rem;
  }
  .postcard .postcard__tagbox {
    justify-content: start;
  }
  .postcard .postcard__img {
    max-width: 300px;
    max-height: 100%;
    transition: transform 0.3s ease;
  }
  .postcard .postcard__text {
    padding: 3rem;
    width: 100%;
  }
  .postcard .media.postcard__text:before {
    content: "";
    position: absolute;
    display: block;
    background: #18151f;
    top: -20%;
    height: 130%;
    width: 55px;
  }
  .postcard:hover .postcard__img {
    transform: scale(1.1);
  }
  .postcard:nth-child(2n+1) {
    flex-direction: row;
  }
  .postcard:nth-child(2n+0) {
    flex-direction: row-reverse;
  }
  .postcard:nth-child(2n+1) .postcard__text::before {
    left: -12px !important;
    transform: rotate(4deg);
  }
  .postcard:nth-child(2n+0) .postcard__text::before {
    right: -12px !important;
    transform: rotate(-4deg);
  }
}
@media screen and (min-width: 1024px) {
  .postcard__text {
    padding: 2rem 3.5rem;
  }

  .postcard__text:before {
    content: "";
    position: absolute;
    display: block;
    top: -20%;
    height: 130%;
    width: 55px;
  }

  .postcard.dark .postcard__text:before {
    background: #18151f;
  }

  .postcard.light .postcard__text:before {
    background: #e1e5ea;
  }
}
/* COLORS */
.postcard .postcard__tagbox .green.play:hover {
  background: #79dd09;
  color: black;
}

.green .postcard__title:hover {
  color: #79dd09;
}

.green .postcard__bar {
  background-color: #79dd09;
}

.green::before {
  background-image: linear-gradient(-30deg, rgba(121, 221, 9, 0.1), transparent 50%);
}

.green:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(121, 221, 9, 0.1), transparent 50%);
}

.postcard .postcard__tagbox .blue.play:hover {
  background: #0076bd;
}

.blue .postcard__title:hover {
  color: #0076bd;
}

.blue .postcard__bar {
  background-color: #0076bd;
}

.blue::before {
  background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 50%);
}

.blue:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(0, 118, 189, 0.1), transparent 50%);
}

.postcard .postcard__tagbox .red.play:hover {
  background: #bd150b;
}

.red .postcard__title:hover {
  color: #bd150b;
}

.red .postcard__bar {
  background-color: #bd150b;
}

.red::before {
  background-image: linear-gradient(-30deg, rgba(189, 21, 11, 0.1), transparent 50%);
}

.red:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(189, 21, 11, 0.1), transparent 50%);
}

.postcard .postcard__tagbox .yellow.play:hover {
  background: #bdbb49;
  color: black;
}

.yellow .postcard__title:hover {
  color: #bdbb49;
}

.yellow .postcard__bar {
  background-color: #bdbb49;
}

.yellow::before {
  background-image: linear-gradient(-30deg, rgba(189, 187, 73, 0.1), transparent 50%);
}

.yellow:nth-child(2n)::before {
  background-image: linear-gradient(30deg, rgba(189, 187, 73, 0.1), transparent 50%);
}

@media screen and (min-width: 769px) {
  .green::before {
    background-image: linear-gradient(-80deg, rgba(121, 221, 9, 0.1), transparent 50%);
  }

  .green:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(121, 221, 9, 0.1), transparent 50%);
  }

  .blue::before {
    background-image: linear-gradient(-80deg, rgba(0, 118, 189, 0.1), transparent 50%);
  }

  .blue:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(0, 118, 189, 0.1), transparent 50%);
  }

  .red::before {
    background-image: linear-gradient(-80deg, rgba(189, 21, 11, 0.1), transparent 50%);
  }

  .red:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(189, 21, 11, 0.1), transparent 50%);
  }

  .yellow::before {
    background-image: linear-gradient(-80deg, rgba(189, 187, 73, 0.1), transparent 50%);
  }

  .yellow:nth-child(2n)::before {
    background-image: linear-gradient(80deg, rgba(189, 187, 73, 0.1), transparent 50%);
  }
}
    </style>
</head>

<body>

    <!-- <div class="main">
        <div class="main2">
            {% for search in object_list%}
            <div class="row">
                <div class="column1">
                <img src="{{search.Hotel_image.url}}" alt="" height="350px
                " width="100%">
                </div>
                <div class="column2">
                <p class="nm">{{search.name}}</p>
                <p class="ct">{{search.city}}</p>
                <div class="btn1">

                    <a href="" class="button"><input type="submit" value="Book Now" class="btn"></a>
                </div>

                </div>
            </div> <br><br>
            {% endfor %}
        </div>
    </div> -->

    <div class="container">
        

        
        
        <section class="light">
            <div class="container py-2">
                <div class="h1 text-center text-dark" id="pageHeaderTitle">Hotels</div>
                {% for search in object_list%}
                <article class="postcard light blue">
                    <a class="postcard__img_link" href="#">
                        <img class="postcard__img" src="{{search.Hotel_image.url}}" alt="Image Title" />
                    </a>
                    <div class="postcard__text t-dark">
                        <h1 class="postcard__title blue"><a href="#">{{search.name}}</a></h1>
                        <div class="postcard__subtitle small">
                            <time datetime="2020-05-25 12:00:00">
                                <i class="fas fa-calendar-alt mr-2"></i>{{search.address}}
                            </time>
                        </div>
                        <div class="postcard__bar"></div>
                        <div class="postcard__preview-txt">{{search.hotel_info}}</div>
                        <ul class="postcard__tagbox">
                            
                            <li class="tag__item play blue">
                                <a href="{% url 'hotel:rooms' hotel=search.name %}"><i class="fas fa-play mr-2"></i>Book Now</a>
                            </li>
                        </ul>
                    </div>
                </article>
                {% endfor %}
                
            </div>
        </section>
    </div>
</body>

</html>

Hotel_booking/Hotel_booking_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate enctype="multipart/form-data">
         {% csrf_token %}
         {% for fm in form %}
         {{fm.label_tag}}{{fm}}{{fm.errors|striptags}} <br><br>

         {% endfor %}
       
        <input type="submit" value="signup">
        <a href="{% url 'hotel:login' %}">Signin</a>
    </form>
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/update_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update_profile</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_p}}

        <input type="submit" value="Update">

    </form>
    
</body>
</html>

Hotel_booking/Hotel_booking_app/templates/userhome.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .navbar{
            display: flex;
            background-color: blue;
            color: white;
            


        }
        .navbar h1{
            display: block;
           
        }
        .nav-items a{
            margin: 1200px; 
            color: white;
           
            align-items: center;
            padding-top: 50;
            border-radius: 25px;

        }
        .nav-items {
            display: flex;
            border-radius: 25px;
            align-items: center;
            
        }
        
        #log{
            padding-top: 50px;
            margin-left: 1050px;
            
        }
        .cm {
            background-color: white;
            display:flex;
            padding-top: 600px;
            
            background-image: url('docker images');
            background-size:100%100%;
            background-attachment:fixed;
        }
        img{
            border-radius: 25px;
            
        }
      
        

    </style>
</head>
<body>
    <div class="navbar">
        <div>
            <h1>Hotel.com</h1>
        <h3>{{qr.first_name}}</h3>
        </div>
        
        <div class="nav-items"  >
           
           <div class="profile">
            <a href="{% url 'hotel:profile' user.id %}" id="pro">
                
                <img src="{{qr.profile_image.url}}" alt="Profile" height="50px"  width="50px"></a>
           </div>
            
                
                      <!-- src="{% static 'image/profile.jpg' %}" alt="Profile" height="25px"  -->
        </div>
    </div>

    
        
    <div  class="cm" style="background-image: url('../static/image/hotel.png.jpg');">
        
        <form action="{% url 'hotel:search' %}" method="get">
                <input type="search" name="search" id="search" placeholder="search city">
                <input type="submit" value="search">
        </form>

        <div>
            {% for search in object_list  %}
    
                {{search.name}} <br>
                {{search.city}} <br>
    
            {% endfor %}
        </div>
        
        
    </div>
     
    
   
</body>
</html>